---
title: "ExcelからRへの進化"
description: "It's good for you"
author: "Andrew Ba Tran"
date: 2018-05-27T21:13:14-05:00
categories: ["R"]
tags: ["R", "RStudio"]
weight: 1
slug: from-excel-to-r
---

Rは、スプレッドシートのデータを操作することに慣れている人にとって素晴らしいものです。
データ分析のためにExcelやGoogle SheetsからRに切り替えるのは大変な手間に思えます。
このオープンソースの統計プログラミング言語は、その能力を拡張することを目的とした数多くのユーザー作成ライブラリを持ち、数字を扱う人々の間で人気が高まってきています。

Rは当初、統計モデルの作成を容易にし、データを調べるための簡単な図を出力するために作成されました。今では、Webサイトのスクレイピング、APIとの通信、美しいインタラクティブチャートや地図の公開といった高度なプロセスを実行できるようになっています。
ほんの数行のコードで全てができます。

 **再現可能な調査** の実践は、学術の世界から非営利団体やジャーナリズムのような他の分野に広がっています。
 他の人が調査を検証または再構築できるように、分析が元のデータ、および方法論またはソフトウェアコードとともに公開されるべきであるというアイデアです。

他の人もあなたのやり方を再現することができます。しかし、より大きな魅力はあなたが他のプロジェクトも再現できるという点にあります。

最も重要なことは、将来プロジェクトの分析をやり直すことができるということです。
Hadley Wickham が[かつて言ったように](https://www.r-bloggers.com/your-most-valuable-collaborator-future-you/):
"どんなプロジェクトにも、少なくとも1人の共同編集者がいます。それは未来のあなたです。過去の自分を呪いたくなるような未来は望まないでしょう"

Excelでは、ユーザーが式を実行したり、並べ替えを行ったり、ピボットテーブルをいくつか作成したりすることはできますが、そのデータに対して行った作業を、同様のデータ構造を持つ別のスプレッドシートにすばやく複製することはできません。
全体のプロセスを段階的に繰り返す必要があります。
Rでデータ分析を行うことの利点は、スプレッドシートを分割して分析するためのスクリプトを書き、それを保存してからコードを少し調整するだけで別のスプレッドシートにも使用できるようになるということです。

理想的なデータジャーナリズムは全てが文書化され再現可能であるべきです。
データ分析がより複雑になり、より大きなデータセットとより高度な計算を含むようになるにつれ、再現性を担保する必要性が劇的に高まります。

再現性があることによって、人々はデータ分析の本質的な内容に集中することができます。
らに、実際に分析に使用したデータとコードが利用できるのであれば、他の人にとって分析がより有用なものになるのです。


-----

<span style="color:gray">
