---
title: "Rの基本、ヘルプ、よくあるミス"
description: "A guide for R basics, common mistakes you might face, and how you might get help"
author: "Andrew Ba Tran"
date: 2018-05-27T21:13:14-05:00
categories: ["R"]
tags: ["R", "basics", "programming"]
weight: 5
slug: r-syntax
---


## Rコードの基本

* `<-` は「代入演算子」として知られています。それは、「左辺の変数を右辺のコードの出力と等しくする」ことです。
* `&`はブール論理でANDを意味します。
* `|`はブール論理ではORを意味します。
* `!`はブール論理ではNOTを意味します。
* テキストとして入力された値、または日付を参照する場合、それらを`"United States"`、または`"2016-07-26"`のように引用符で囲みます。数字は引用符で囲みません。
* リストとして複数の値を入力する場合は、値をコンマで区切り、関数`c`を使用して結合します。ここに例を示します。`c("2017-07-26","2017-08-04")`
* スプレッドシートと同じように、コロンを使用して値の範囲を指定できます。例えば、`c(1:10)`は1から10までの整数のリストを作成する関数です。
* いくつかの一般的な演算子：
	* `+` `-` 加算、減算
	* `*` `/` 乗算、除算
	* `>` `<` 大なり、小なり
	* `>=` `<=` 以上、以下
	* `!=` 等しくない
* **等号は混乱を招きがちです**
	* `==` は、両辺のオブジェクトが等しいかどうかをテストします。これはデータのフィルタリングによく使われます。
	* `=` はオブジェクトを値と等しくします。`<-`に似ていますが、関数の中で使います。
* null値の扱い
	* Nullは `NA`と示されます。
	* `is.na(x)` は変数`x`の中でNULLを探します。
	* `!is.na(x)` は逆に `x`の中でNULLではない値を探します。

`is.na()`は**関数**です。関数の後に括弧があり、括弧内のコード/データに作用します。

{{% notice disclaimer %}}
Rのオブジェクト名および変数名はスペースを含んではいけません。
{{% /notice %}}



## Rの作業スペース

* 現在のR作業環境
* 任意のユーザー定義オブジェクト（ベクトル、データフレーム、関数など）を含みます。

| 関数 | 機能 |
| ------ | -------------------------------------------------- |
| `getwd()`   | 現在の作業ディレクトリを一覧表示します。 |
| `setwd("mydirectory")` | 現在の作業ディレクトリを自分のディレクトリに変更します。 |
| `ls()`    | 現在の作業領域内のオブジェクトを一覧表示します。 |
| `rm(object)`    | オブジェクトを削除します。 |
| `save(objectlist, file="myfile)`    | 特定のオブジェクトをファイルに保存します。 |
| `load("myfile")`    | 現在の作業領域に作業スペースを読み込みます (初期設定は.RData) |
## パッケージ

* パッケージとはきちんと定義されたRの関数、データ、およびコンパイル済みコードのコレクションのことです。
* Rの機能を大幅に拡張します。
* CRAN上には何千ものユーザー作成パッケージがあります。
	* [https://cran.r-project.org/web/packages](https://cran.r-project.org/web/packages/)


{{% notice tip %}}
Macユーザーは、Apple以外の開発者が作成したアプリをインストールできるようにセキュリティ設定を変更する必要があるかもしれません。エラーが発生した場合は [設定を変更してみてください。](https://www.youtube.com/watch?v=xFpVqkyXFy4).
{{% /notice %}}


## 困ったときは

| 関数 | 機能 |
| ------ | -------------------------------------------------- |
| `help.start()`   | 一般的なヘルプ |
| `help("foo")` or `?foo` | fooについてのヘルプ（引用符はオプションです） |
| `help.search("foo")` or `??foo`    | ヘルプシステムで文字列fooに合致する事例を検索します。 |
| `example("foo")`    | fooの例（引用符はオプションです）) |

## パッケージを使った作業

* install.packages("*packagename*")
* update.packages()


* library(*packagename*)
* help(package="*packagename*")


* library() #どんなパッケージがライブラリにあるのか表示します。
* search() #どんなパッケージがロードされているか表示します。

## よくある間違い

* **大文字、小文字の間違い**
	* help()、Help()、そしてHELP()は3つの異なる関数です（そして最初のものだけが動作します）。
* **引用符を忘れる**
	* install.packages("gclus") は機能しますが、install.packages(gclus) はエラーとなります。
* **関数の後に括弧がない**
* HELPではなくhelp()。引数がない場合でも、（）は必要です。
* **Windowsでパス名に `\` を使用する**
	* Rはバックスラッシュをエスケープ文字と見なします。
	* `setwd("c:\mydata")` はエラーとなります。 `setwd("c:/mydata")` か `setwd("c:\\mydata")` としましょう。
* **ロードされていないパッケージの関数を使用する**
	*  `str_trim()` という関数は **stringr** パッケージに含まれています。
	* パッケージをロードしないで使用しようとすると、エラーが発生します。

